---
# Определение workflow с именем "Build site and Deploy to FTP"
name: Build site and Deploy to FTP

# Запуск workflow при каждом push в ветку develop
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установка недостающих plantuml и graphviz
      - name: Install APT packages
        run: |
          sudo apt-get update
          sudo apt-get install graphviz plantuml --yes --no-install-recommends

      # Шаг 3: Установка зависимостей из файла requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Шаг 4: Генерация документации
      - name: Build documentation
        run: make html

      # Шаг 5: Загрузка на FTP
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}  # Используется секрет с адресом FTP-сервера
          username: ${{ secrets.FTP_USERNAME }}  # Используется секрет с именем пользователя
          password: ${{ secrets.FTP_PASSWORD }}  # Используется секрет с паролем
          server-dir: /techwriters.ru/  # Путь на FTP-сервере, куда загружать файлы
          local-dir: build/html/  # Путь к сгенерированным файлам, которые будут загружены
